#+TITLE: 1 Sprint Review 
#+AUTHOR: Boogie
#+SUBTITLE: DSC 205 - Advanced introduction to data science
#+STARTUP: overview hideblocks indent
#+OPTIONS: toc:nil num:nil ^:nil
#+PROPERTY: header-args:R :session *R* :results output :exports both :noweb yes

Problem
 - I am currently creating a website using html and css for a web
   development class this semester. I am having trouble with making my
   website look cool. To help solve this, I think  using the R package
   "gganimate" will improve the overall theme and aesthetic of the
   webpage.

Reason
 - This problem is interesting to me because it will help improve my
   project for another class. Also, being proficient in something
   like gganimate could help for the future in other web dev
   projects.

Constraints
 - There are a lot of constraints. I do not know much about R packages
   or html/css stylesheets which will result in a lot of
   learning. (that is not a bad thing!) I am also not sure if you can
   use R packages for something like html code/web development.

Goals and Non Goals
 - Goals
   - I would like to create animations for my website.
   - I would like to learn more about ggplot and gganimate

Metrics
 - I would measure the success of my project based on the progress I
   have made towards creating things like table animations, page
   animations, trendline animations, and overall, just knowing more
   later than what I do now planning this project.

