#+TITLE: CONDITIONS AND LOOPS - CONDITIONAL STATEMENTS - IF ELSE
#+AUTHOR: Marcus Birkenkrahe
#+SUBTITLE: DSC 205 - Advanced introduction to data science
#+STARTUP: overview hideblocks indent
#+OPTIONS: toc:nil num:nil ^:nil
#+PROPERTY: header-args:R :session *R* :results output :exports both :noweb yes
* README

This practice file accompanies the [[https://github.com/birkenkrahe/ds2/blob/main/org/3_conditions.org][lecture]] on conditional
statements. You will learn:

- [ ] 

Download the *raw* practice file [[https://raw.githubusercontent.com/birkenkrahe/ds2/main/org/3_conditions_practice.org][from GitHub]] and save it as
~3_conditions_practice.org~.

To test your Emacs mettle, open it on the CMD line with the command
~emacs -nw~ (graphics are not needed for this exercise).

* TODO Identify and pledge yourself

1) In Emacs, replace the placeholder ~[yourname]~ at the top of this
   file by your own name and write ~(pledged)~ next to it
2) Go with the cursor on the headline and hange the ~TODO~ label to ~DONE~
   by entering ~S-<right>~ ("Shift + right-arrow").

* TODO Exercises

1) Create two vectors:
   #+begin_src R
     vec1 <- c(2,1,1,3,2,1,0)
     vec2 <- c(3,8,2,2,0,0,0)
   #+end_src

2) Without executing them, determine which of the following ~if~
   statements would result in the string being printed to the
   console. Confirm your answers in R.

   /Tip:/ the ~all~ functions checks if all of its logical argument values
   are true.

   #+begin_example R
     if((vec1[1]+vec2[2])==10){cat("Print me!\n")}
   #+end_example

   #+begin_example R
     if(vec1[1]>=2&&vec2[1]>=2){cat("Print me!\n")}
   #+end_example

   #+begin_example R
     if(all((vec2-vec1)[c(2,6)]<7)){cat("Print me!\n")}
   #+end_example

   #+begin_example R
     if(!is.na(vec2[3])){cat("Print me!\n")}
     #+end_example

3) Using ~vec1~ and ~vec2~, write and execute a line of code that
   multiplies the corresponding elements of the two vectors together
   if their sum is greater than ~3~. Otherwise, the code should simply
   sum the two elements.
   #+begin_src R

   #+end_src
